sudo: required
dist: trusty

language: haxe

os:
  - linux
  
haxe:
  - "3.4.0"
  - development
  
matrix:
  allow_failures:
    - haxe: development
    
install:
  - haxelib install travix
  - haxelib install asys
  - haxelib run travix install

script:
  - haxelib run travix js
  
  - haxelib run travix node
  - haxelib run travix php
  - haxelib run travix interp
  #- haxelib run travix php7
  - haxelib run travix neko
  - haxelib run travix java
  
  - haxelib run travix node -lib asys
  - haxelib run travix php -lib asys
  - haxelib run travix interp -lib asys
  #- haxelib run travix php7 -lib asys
  - haxelib run travix neko -lib asys
  - haxelib run travix java -lib asys
